openapi: "3.0.0"
info:
  version: 1.0.0
  title: Swagger Petstore
  description: |-
    ## Пример описания сервисов и моделей. 
    _Данный вид разбиения на папки, считать всего лишь демонстрацией такой возможности_
  license:
    name: MIT
servers:
  - url: http://localhosts/v1
paths:
  /pets:
    $ref: ./petstore/paths.yaml#/~1pets
  /pets/{petId}:
    $ref: ./petstore/paths.yaml#/~1pets~1{petId}
components:
  securitySchemes:
    OAuth2:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: https://example.com/oauth/authorize
          tokenUrl: https://example.com/oauth/token
          scopes:
            read: Grants read access
            write: Grants write access
            admin: Grants access to admin operations
